"""Document hash projection helpers.

LightRAG document ids generated by Twin's ingestion hook use
``compute_mdhash_id(content, prefix="doc-")``. When that exact shape is
present, the suffix is the content-derived digest and can be exposed as
metadata. Anything else is left untouched.
"""

from __future__ import annotations

from string import hexdigits
from typing import Any


HASH_METADATA_KEYS = (
    "content_hash",
    "contentHash",
    "file_hash",
    "fileHash",
    "sha256",
    "sha1",
    "md5",
    "checksum",
)


def enrich_metadata_with_document_hash(
    metadata: dict[str, Any],
    doc_id: str,
) -> dict[str, Any]:
    """Return metadata carrying a real document hash when one is available."""

    enriched = dict(metadata)
    if _has_existing_hash(enriched):
        return enriched

    digest = lightrag_content_hash_from_doc_id(doc_id)
    if digest is None:
        return enriched

    enriched["content_hash"] = digest
    enriched["content_hash_source"] = "lightrag_doc_id"
    return enriched


def lightrag_content_hash_from_doc_id(doc_id: str) -> str | None:
    """Extract the content digest from a LightRAG ``doc-<32 hex>`` id."""

    value = str(doc_id or "")
    if not value.startswith("doc-"):
        return None

    digest = value.removeprefix("doc-")
    if len(digest) != 32:
        return None
    if any(char not in hexdigits for char in digest):
        return None
    return digest.lower()


def _has_existing_hash(metadata: dict[str, Any]) -> bool:
    for key in HASH_METADATA_KEYS:
        value = metadata.get(key)
        if isinstance(value, str) and value.strip():
            return True
    return False
