sonar.projectKey=twindb-lightrag-memgraph
sonar.projectName=twindb-lightrag-memgraph
sonar.projectVersion=0.4.1

sonar.sources=src
sonar.tests=tests
sonar.language=python
sonar.python.version=3.10,3.11,3.12,3.13,3.14

sonar.sourceEncoding=UTF-8
sonar.python.coverage.reportPaths=coverage.xml
sonar.exclusions=**/.venv/**,**/node_modules/**,**/__pycache__/**
